In [3]:
import pandas as pd
import h2o
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer

In [42]:
#all_tweets = pd.read_csv('/home/ubuntu/toolkit/realdonaldtrump_tweets.csv')
allDtweets = pd.read_csv('/home/ubuntu/toolkit/sentiment/realdonaldtrump_tweets.csv')

In [69]:
allDtweets.shape

(3217, 7)

In [43]:
allHtweets = pd.read_csv('/home/ubuntu/toolkit/sentiment/hillaryclinton_tweets.csv')

In [70]:
allHtweets.shape

(3230, 7)

In [44]:
allDtweets.columns

Index([u'Unnamed: 0', u'id', u'text', u'created_at', u'favorite_count',
       u'retweet_count'],
      dtype='object')

In [46]:
allHtweets.head()

,Unnamed: 0,id,text,created_at,favorite_count,retweet_count
0,0,783440463122554880,If Trump's decisiveness in choosing Mike Pence...,Tue Oct 04 22:55:36 +0000 2016,608.0,272.0
1,1,783435753141440513,Mike Pence has actually signed into law hatefu...,Tue Oct 04 22:36:53 +0000 2016,892.0,505.0
2,2,783427721648967681,Before Mike Pence takes the debate stage to de...,Tue Oct 04 22:04:58 +0000 2016,1960.0,958.0
3,3,783424369754304512,Post-traumatic stress isn't something strong p...,Tue Oct 04 21:51:39 +0000 2016,4932.0,1902.0
4,4,783421695382196224,“I learned that preparation is important.” —Hi...,Tue Oct 04 21:41:02 +0000 2016,2514.0,593.0

In [47]:
allDtweets.head()

,Unnamed: 0,id,text,created_at,favorite_count,retweet_count
0,0,783436108176629760,Thank you ARIZONA! This is a MOVEMENT like nob...,Tue Oct 04 22:38:18 +0000 2016,4229.0,1729.0
1,1,783393314309484544,My childcare plan makes a difference for worki...,Tue Oct 04 19:48:15 +0000 2016,11110.0,4719.0
2,2,783391423663964160,I will be watching the great Governor @Mike_Pe...,Tue Oct 04 19:40:44 +0000 2016,14211.0,4809.0
3,3,783390310969651200,"Join me in Reno, Nevada tomorrow at 3:30pm! #A...",Tue Oct 04 19:36:19 +0000 2016,5743.0,2053.0
4,4,783149570721144832,"Join me in Reno, Nevada on Wednesday at 3:30pm...",Tue Oct 04 03:39:42 +0000 2016,13895.0,6189.0

In [48]:
allDtweets["author"] = "Trump"

In [49]:
allDtweets.head()

,Unnamed: 0,id,text,created_at,favorite_count,retweet_count,author
0,0,783436108176629760,Thank you ARIZONA! This is a MOVEMENT like nob...,Tue Oct 04 22:38:18 +0000 2016,4229.0,1729.0,Trump
1,1,783393314309484544,My childcare plan makes a difference for worki...,Tue Oct 04 19:48:15 +0000 2016,11110.0,4719.0,Trump
2,2,783391423663964160,I will be watching the great Governor @Mike_Pe...,Tue Oct 04 19:40:44 +0000 2016,14211.0,4809.0,Trump
3,3,783390310969651200,"Join me in Reno, Nevada tomorrow at 3:30pm! #A...",Tue Oct 04 19:36:19 +0000 2016,5743.0,2053.0,Trump
4,4,783149570721144832,"Join me in Reno, Nevada on Wednesday at 3:30pm...",Tue Oct 04 03:39:42 +0000 2016,13895.0,6189.0,Trump

In [50]:
allHtweets["author"] = "Clinton"

In [51]:
allHtweets.head()

,Unnamed: 0,id,text,created_at,favorite_count,retweet_count,author
0,0,783440463122554880,If Trump's decisiveness in choosing Mike Pence...,Tue Oct 04 22:55:36 +0000 2016,608.0,272.0,Clinton
1,1,783435753141440513,Mike Pence has actually signed into law hatefu...,Tue Oct 04 22:36:53 +0000 2016,892.0,505.0,Clinton
2,2,783427721648967681,Before Mike Pence takes the debate stage to de...,Tue Oct 04 22:04:58 +0000 2016,1960.0,958.0,Clinton
3,3,783424369754304512,Post-traumatic stress isn't something strong p...,Tue Oct 04 21:51:39 +0000 2016,4932.0,1902.0,Clinton
4,4,783421695382196224,“I learned that preparation is important.” —Hi...,Tue Oct 04 21:41:02 +0000 2016,2514.0,593.0,Clinton

In [75]:
all_tweets = pd.concat([allHtweets, allDtweets])

In [76]:
all_tweets.shape

(6447, 7)

In [77]:
all_tweets.count()

Unnamed: 0        6447
id                6447
text              6447
created_at        6447
favorite_count    6447
retweet_count     6447
author            6447
dtype: int64

In [78]:
all_tweets.head()

,Unnamed: 0,id,text,created_at,favorite_count,retweet_count,author
0,0,783440463122554880,If Trump's decisiveness in choosing Mike Pence...,Tue Oct 04 22:55:36 +0000 2016,608.0,272.0,Clinton
1,1,783435753141440513,Mike Pence has actually signed into law hatefu...,Tue Oct 04 22:36:53 +0000 2016,892.0,505.0,Clinton
2,2,783427721648967681,Before Mike Pence takes the debate stage to de...,Tue Oct 04 22:04:58 +0000 2016,1960.0,958.0,Clinton
3,3,783424369754304512,Post-traumatic stress isn't something strong p...,Tue Oct 04 21:51:39 +0000 2016,4932.0,1902.0,Clinton
4,4,783421695382196224,“I learned that preparation is important.” —Hi...,Tue Oct 04 21:41:02 +0000 2016,2514.0,593.0,Clinton

In [79]:
all_tweets.tail()

,Unnamed: 0,id,text,created_at,favorite_count,retweet_count,author
3212,3244,685644333022851072,Great even in SC tonight! Fire Marshall would ...,Sat Jan 09 02:08:42 +0000 2016,6390.0,1925.0,Trump
3213,3245,685606815267221504,"Will be at venue, in wonderful South Carolina,...",Fri Jan 08 23:39:37 +0000 2016,4761.0,1239.0,Trump
3214,3246,685600012043202560,#FoxNews Poll - THANK YOU!\n#MakeAmericaGreatA...,Fri Jan 08 23:12:35 +0000 2016,5775.0,2434.0,Trump
3215,3247,685590843181416448,#MakeAmericaGreatAgain #Trump2016 https://t.co...,Fri Jan 08 22:36:09 +0000 2016,6283.0,2570.0,Trump
3216,3248,685584095120887809,Love seeing union &amp; non-union members alik...,Fri Jan 08 22:09:20 +0000 2016,7250.0,2639.0,Trump

In [80]:
all_tweets.columns

Index([u'Unnamed: 0', u'id', u'text', u'created_at', u'favorite_count',
       u'retweet_count', u'author'],
      dtype='object')

In [81]:
all_tweets = all_tweets[["id", "text", "author"]]
#all_tweets = all_tweets[[u"id", u"text", u"author"]]

In [82]:
all_tweets.shape

(6447, 3)

In [83]:
all_tweets.columns

Index([u'id', u'text', u'author'], dtype='object')

In [84]:
all_tweets.dtypes

id         int64
text      object
author    object
dtype: object

In [85]:
all_tweets["tweets_id"] = all_tweets["id"].astype("str")

In [86]:
all_tweets.dtypes

id            int64
text         object
author       object
tweets_id    object
dtype: object

In [90]:
all_tweets = all_tweets.drop(["id"],1)

In [91]:
all_tweets.dtypes

text         object
author       object
tweets_id    object
dtype: object

In [92]:
all_tweets["tweets_text"] = all_tweets["text"].apply(lambda x: x.decode('utf-8'))

In [93]:
all_tweets.dtypes

text           object
author         object
tweets_id      object
tweets_text    object
dtype: object

In [94]:
all_tweets = all_tweets.drop(["text"],1)
# We could have done this too
# all_tweets = all_tweets.drop(["text", "id"],1)

In [95]:
all_tweets.dtypes

author         object
tweets_id      object
tweets_text    object
dtype: object

In [96]:
all_tweets.head()

,author,tweets_id,tweets_text
0,Clinton,783440463122554880,If Trump's decisiveness in choosing Mike Pence...
1,Clinton,783435753141440513,Mike Pence has actually signed into law hatefu...
2,Clinton,783427721648967681,Before Mike Pence takes the debate stage to de...
3,Clinton,783424369754304512,Post-traumatic stress isn't something strong p...
4,Clinton,783421695382196224,“I learned that preparation is important.” —Hi...

In [108]:
# shuffling the df
all_tweets = all_tweets.sample(frac=1)

In [109]:
all_tweets.shape

(6447, 3)

In [110]:
all_tweets.head()

,author,tweets_id,tweets_text
2001,Clinton,755750045148966912,Five disturbing things the GOP officially stan...
309,Clinton,780540877047341057,“You didn’t blame Little John or Meat Loaf. Yo...
1008,Clinton,768890043448647680,Trump is reinforcing harmful stereotypes and o...
3053,Trump,690315667636023296,#Trump2016 #MakeAmericaGreatAgain https://t.co...
2212,Clinton,752631205665837060,RT @HillaryforPA: PA's Senate is voting on a r...

In [111]:
all_tweets = all_tweets.reset_index()

In [112]:
all_tweets.head()

,index,author,tweets_id,tweets_text
0,2001,Clinton,755750045148966912,Five disturbing things the GOP officially stan...
1,309,Clinton,780540877047341057,“You didn’t blame Little John or Meat Loaf. Yo...
2,1008,Clinton,768890043448647680,Trump is reinforcing harmful stereotypes and o...
3,3053,Trump,690315667636023296,#Trump2016 #MakeAmericaGreatAgain https://t.co...
4,2212,Clinton,752631205665837060,RT @HillaryforPA: PA's Senate is voting on a r...

In [113]:
all_tweets = all_tweets.drop(["index"],1)

In [114]:
all_tweets.head()

,author,tweets_id,tweets_text
0,Clinton,755750045148966912,Five disturbing things the GOP officially stan...
1,Clinton,780540877047341057,“You didn’t blame Little John or Meat Loaf. Yo...
2,Clinton,768890043448647680,Trump is reinforcing harmful stereotypes and o...
3,Trump,690315667636023296,#Trump2016 #MakeAmericaGreatAgain https://t.co...
4,Clinton,752631205665837060,RT @HillaryforPA: PA's Senate is voting on a r...

In [115]:
all_tweets.tail()

,author,tweets_id,tweets_text
6442,Clinton,750729972407468034,"And the Trump Taj Mahal, which Donald called t..."
6443,Clinton,728230016656363520,"""Do you still believe that Muslims should be b..."
6444,Trump,687717134890307588,Do you think Iran would have acted so tough if...
6445,Trump,707226089496690688,"""@EricTrump: Wishing our father tremendous luc..."
6446,Trump,690672420433178624,Wow! New National Zogby Poll just out:.TRUMP 4...

In [119]:
all_tweets.shape

(6447, 3)

In [120]:
tfidf_tweets = all_tweets["tweets_text"].values

In [122]:
tfidf_tweets.shape

(6447,)

In [126]:
tfidf_tweets.ctypes

In [127]:
# Initialize our TF-IDF Vectorizer & create our (sparse) TF-IDF matrix
tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform(tfidf_tweets)

In [129]:
# Note: it is a numpy array
tfidf_matrix

<6447x12987 sparse matrix of type '<type 'numpy.float64'>'
	with 110637 stored elements in Compressed Sparse Row format>

In [130]:
# Convert our matrix to a dense matrix and convert to a DataFrame, adding the actual column names
dense = pd.DataFrame(tfidf_matrix.todense(), columns=tfidf_vectorizer.get_feature_names())

In [134]:
# Note: it is pandas data frame
dense.shape

(6447, 12987)

In [132]:
dense.head()

,00,000,007cigarjoe,00gnh9nlet,00pm,016,02,02nmqn3znq,04qqpgylt7,04t1bhwlvc,...,zy7vpfrsdz,zyaj0hiq0v,zyhli,zyr,zyrctsfmsq,zzl2sc29dn,él,única,únicos,⁰⁰
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [136]:
# Re-join with our original dataset
output_tweets = pd.concat([all_tweets, dense], 1)

In [137]:
output_tweets.shape

(6447, 12990)

In [138]:
output_tweets.head()

,author,tweets_id,tweets_text,00,000,007cigarjoe,00gnh9nlet,00pm,016,02,...,zy7vpfrsdz,zyaj0hiq0v,zyhli,zyr,zyrctsfmsq,zzl2sc29dn,él,única,únicos,⁰⁰
0,Clinton,755750045148966912,Five disturbing things the GOP officially stan...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Clinton,780540877047341057,“You didn’t blame Little John or Meat Loaf. Yo...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Clinton,768890043448647680,Trump is reinforcing harmful stereotypes and o...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Trump,690315667636023296,#Trump2016 #MakeAmericaGreatAgain https://t.co...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Clinton,752631205665837060,RT @HillaryforPA: PA's Senate is voting on a r...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [139]:
output_tweets = output_tweets.drop(["tweets_text"],1)

In [140]:
output_tweets.head()

,author,tweets_id,00,000,007cigarjoe,00gnh9nlet,00pm,016,02,02nmqn3znq,...,zy7vpfrsdz,zyaj0hiq0v,zyhli,zyr,zyrctsfmsq,zzl2sc29dn,él,única,únicos,⁰⁰
0,Clinton,755750045148966912,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Clinton,780540877047341057,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Clinton,768890043448647680,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Trump,690315667636023296,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Clinton,752631205665837060,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [141]:
output_tweets.tail()

,author,tweets_id,00,000,007cigarjoe,00gnh9nlet,00pm,016,02,02nmqn3znq,...,zy7vpfrsdz,zyaj0hiq0v,zyhli,zyr,zyrctsfmsq,zzl2sc29dn,él,única,únicos,⁰⁰
6442,Clinton,750729972407468034,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6443,Clinton,728230016656363520,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6444,Trump,687717134890307588,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6445,Trump,707226089496690688,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6446,Trump,690672420433178624,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

We could have also done some further cleaning of the data, such as excluding urls from our Tweets text (right now, strings such as “zy7vpfrsdz” get their own feature column as the NLTK vectorizer treats them as words). Our not doing this won’t affect our model as the urls are unique, but it might save on space and time. Another strategy could be to stem words, treating words as their root (so ‘hearing’ and ‘heard’ would both be coded as ‘hear’).

In [142]:
# Note: This step will take time to write to disk - (Make sure)
output_tweets.to_csv("/home/ubuntu/toolkit/tfidf_tweets.csv",  encoding='utf-8')

In [143]:
# H2O Specific commands
h2o.connect()

Connecting to H2O server at http://localhost:54321... successful.

--------------------------  ------------------------
H2O cluster uptime:         17 days 14 hours 52 mins
H2O cluster version:        3.11.0.99999
H2O cluster version age:    1 month and 29 days
H2O cluster name:           ubuntu
H2O cluster total nodes:    1
H2O cluster free memory:    8.69 Gb
H2O cluster total cores:    8
H2O cluster allowed cores:  8
H2O cluster status:         locked, healthy
H2O connection url:         http://localhost:54321
H2O connection proxy:
Python version:             2.7.12 final
--------------------------  ------------------------

In [144]:
output_tweets.h2o = pd.DataFrame(output_tweets)

In [145]:
output_tweets.h2o

,author,tweets_id,00,000,007cigarjoe,00gnh9nlet,00pm,016,02,02nmqn3znq,...,zy7vpfrsdz,zyaj0hiq0v,zyhli,zyr,zyrctsfmsq,zzl2sc29dn,él,única,únicos,⁰⁰
0,Clinton,755750045148966912,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Clinton,780540877047341057,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Clinton,768890043448647680,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Trump,690315667636023296,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Clinton,752631205665837060,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,Trump,712645789953167360,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,Trump,689173145513791488,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,Clinton,768864106656956420,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,Clinton,754348981648515072,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,Trump,692457315941900288,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,Clinton,766302658592399360,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,Trump,748163517455413248,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,Trump,748289375801323520,0.507023,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,Trump,736875933999697920,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,Trump,718626552704077824,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,Trump,729332727665790976,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,Trump,768448216744488960,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,Clinton,750733325845794816,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,Clinton,735943366937042945,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,Clinton,771379484721311744,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,Trump,725824909151199232,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,Clinton,730777600902242304,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,Trump,740708673694076928,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23,Clinton,771031343841116161,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24,Trump,749970824766091264,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25,Clinton,775759018149179392,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26,Trump,735125552064024577,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,Clinton,755420257125212161,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,Clinton,752900102189096961,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29,Clinton,757989498982658049,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6417,Clinton,756899892212166656,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6418,Clinton,763803468347928577,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6419,Trump,750678866532990977,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6420,Clinton,728294044632129537,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6421,Clinton,781150396966404096,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6422,Clinton,758476802943627264,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6423,Trump,695707547395891202,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6424,Clinton,756955836191154176,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6425,Trump,686552289516105728,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6426,Clinton,753628337206165504,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6427,Clinton,758439187532148736,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6428,Clinton,747448065011879936,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6429,Clinton,762076523432116224,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6430,Trump,694885775431835648,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6431,Trump,714411420104925184,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6432,Trump,752906803810279424,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6433,Clinton,751541323346374656,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6434,Trump,728529524468682754,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6435,Clinton,776862331682877440,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6436,Trump,762982142783676416,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6437,Trump,749934450868387840,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6438,Clinton,758471347626541056,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6439,Trump,729301847031349250,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6440,Trump,742695148241313792,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6441,Trump,708158520831553536,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6442,Clinton,750729972407468034,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6443,Clinton,728230016656363520,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6444,Trump,687717134890307588,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6445,Trump,707226089496690688,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6446,Trump,690672420433178624,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [146]:
# Converting pandas dataframe to h2o datafraeme 
# It will take some time so please make sure you have time alloted
h2o.H2OFrame(output_tweets.h2o)

UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 4: ordinal not in range(128)